In [2]:
import numpy as np

In [4]:
np?

<h2>Most Important to Remember</h2>

Numpy's main dta object is **ndarray** - a.k.a n-dimensional array.

Remember that unlike Python lists, NumPy is constrained to arrays that **all contain the same type**. 

In [30]:
print(np.array([1, 4, 2, 5, 3]))

#If types do not match, NumPy will upcast if possible (here, integers are up-cast to floating point):
print(np.array([3.14, 4, 2, 3])) 

#If we want to explicitly set the data type of the resulting array, we can use the dtype keyword:
print(np.array([3.14, 4, 2, 3], dtype='float32'))

[1 4 2 5 3]
[3.14 4.   2.   3.  ]
[3.14 4.   2.   3.  ]


Finally, unlike Python lists, NumPy arrays can explicitly be multi-dimensional; here's one way of initializing a multidimensional array using a list of lists:

In [9]:
# nested lists result in multi-dimensional arrays
np.array([range(i, i + 3) for i in [2, 4, 6]])

array([[2, 3, 4],
       [4, 5, 6],
       [6, 7, 8]])

<h2>Basic Array Manipulation Demo </h2>

- Attributes of arrays: Determining the size, shape, memory consumption, and data types of arrays
- Indexing of arrays: Getting and setting the value of individual array elements
- Slicing of arrays: Getting and setting smaller subarrays within a larger array
- Reshaping of arrays: Changing the shape of a given array
- Joining and splitting of arrays: Combining multiple arrays into one, and splitting one array into many

In [12]:
np.random.seed(0)  # seed for reproducibility

x1 = np.random.randint(10, size=6)  # One-dimensional array
x2 = np.random.randint(10, size=(3, 4))  # Two-dimensional array
x3 = np.random.randint(10, size=(3, 4, 5))  # Three-dimensional array

In [24]:
print("ndim: ", x3.ndim)  # number of dimension
print("shape:", x3.shape) # shape = size of each dimention
print("size: ", x3.size)  # 3*4*5 =  total size
print("dtype:",    x3.dtype)   #dateypte of the array
print("itemsize:", x3.itemsize, "bytes") #lists the size (in bytes) of each array element
print("nbytes:",   x3.nbytes, "bytes") # total size = 8 bytes * 60 items = 480bytes

ndim:  3
shape: (3, 4, 5)
size:  60
dtype: int64
itemsize: 8 bytes
nbytes: 480 bytes


<h3>Array Indexing</h3>

In [26]:
# In a one-dimensional array, 
# the ith value (counting from zero) can be accessed by specifying the desired index in square brackets, just as with Python lists:
print(x1)
print(x1[0])
print(x1[-1]) # negative index form the end of the array
print(x1[-2]) 

[5 0 3 3 7 9]
5
9
7


In [32]:
#In a multi-dimensional array
#items can be accessed using a comma-separated tuple of indices:
print(x2)
print(x2[0,0])
print(x2[2,-1])

[[3 5 2 4]
 [7 6 8 8]
 [1 6 7 7]]
3
7


<h3> Array Slicing</h3>

we can also use square bracket to access subarrays with the slice notation, marked by the colon (:) character. 
The NumPy slicing syntax follows that of the standard Python list; to access a slice of an array x, use this:

`x[start:stop:step]`

If any of these are unspecified, they default to the values `start=0, stop=size of dimension, step=1`. We'll take a look at accessing sub-arrays in one dimension and in multiple dimensions.

In [41]:
x1 = np.arange(10)

print(x1)
print(x1[0:4])
print(x1[0:4:2])

print(x1[:5]) # till index 5
print(x1[5:]) # start from index 5

[0 1 2 3 4 5 6 7 8 9]
[0 1 2 3]
[0 2]
[0 1 2 3 4]
[5 6 7 8 9]


In [59]:
# a useful trick to reverse array
# when the step value is negative. 
# the defaults for start and stop are swapped.

print(x1)
print(x1[::-1])  # all elements, reversed
print(x1[5:2])
print(x1[5:2:-1])  # reversed every other from index 5

[0 1 2 3 4 5 6 7 8 9]
[9 8 7 6 5 4 3 2 1 0]
[]
[5 4 3]


In [50]:
# Multi dimensional array
print(x2)
print(x2[1:,1:3]) #dim 1:[1:], dim 2[1:3]

[[3 5 2 4]
 [7 6 8 8]
 [1 6 7 7]]
[[6 8]
 [6 7]]


*Note*: Array slices in Numpy (in contrast to in Python) are **views** rather than copies of the array data.
Mocifying the slice will also modify the original arrays.

In [63]:
print(x2)
x2_sub_view = x2[:2,:2]
# use .copy() to make a copy of the view
x2_sub_copy = x2[:2, :2].copy()

print(x2_sub_view)
print(x2_sub_copy)



x2_sub_copy[0, 0] = 42
print(x2_sub_copy)
print(x2)

[[3 5 2 4]
 [7 6 8 8]
 [1 6 7 7]]
[[3 5]
 [7 6]]
[[3 5]
 [7 6]]
[[42  5]
 [ 7  6]]
[[3 5 2 4]
 [7 6 8 8]
 [1 6 7 7]]


<h2>Universal Functions： How to efficitenly operate Arrays </h2>

The key to making Numpy Computation fast is to use *vectorized operations*, generally implemented through NumPy's universal functions (ufuncs). 
也就是直接在array上操作，而不是for loop